modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
#issueTrackerURL="https://github.com/Samlegamer/PotionRingReforged/issues" #optional

[[mods]] #mandatory

modId="potionring" #mandatory
version="1.18.2-1.0" #mandatory
displayName="Potion Ring" #mandatory
#updateJSONURL="" #optional
#displayURL="https://www.curseforge.com/minecraft/mc-mods/potion-ring-reforged" #optional
logoFile="icon.png" #optional
credits="Vazkii original creator of Potion Fingers Mod" #optional
authors="Samlegamer" #optional
description='''
A port of the Finger Potion Mod to Minecraft 1.18.2!
'''

[[dependencies.potionring]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="AFTER"
    side="BOTH"

[[dependencies.potionring]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.potionring]]
    modId = "curios"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"