modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Samlegamer/PotionRingReforged/issues"
[[mods]] #mandatory
modId="potionring"
version="1.20-1.1"
displayName="Potion Rings"
displayURL="https://www.curseforge.com/minecraft/mc-mods/potion-ring-reforged"
logoFile="icon.png"
credits="Vazkii original creator of Potion Fingers Mod"
authors="Samlegamer"

description='''A port of the Finger Potion Mod to Minecraft 1.20 !'''

[[dependencies.potionring]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.potionring]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.potionring]]
    modId = "curios"
    mandatory = false
    ordering = "AFTER"
    versionRange = "NONE"
